//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeropriatiyaKrush
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        
        public Entities1()
            : base("name=Entities1")
        {
        }
        private static Entities1 _context;

        public static Entities1 GetContext()
        {
            if (_context == null)
            {
                _context = new Entities1();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Мероприятия> Мероприятия { get; set; }
        public virtual DbSet<Страны> Страны { get; set; }
        public virtual DbSet<Жюри> Жюри { get; set; }
        public virtual DbSet<Модераторы> Модераторы { get; set; }
        public virtual DbSet<Организаторы> Организаторы { get; set; }
        public virtual DbSet<Участники> Участники { get; set; }
    }
}
