//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeropriatiyaKrush
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.Модераторы = new HashSet<Модераторы>();
        }
    
        public double ID { get; set; }
        public string Событие { get; set; }
        public System.DateTime DATE { get; set; }
        public double DAYS { get; set; }
        public double Город { get; set; }
    
        public virtual Город Город1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Модераторы> Модераторы { get; set; }
    }
}
