//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeropriatiyaKrush
{
    using System;
    using System.Collections.Generic;
    
    public partial class Модераторы
    {
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public string Почта { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public double Страна { get; set; }
        public string Телефон { get; set; }
        public string Направление { get; set; }
        public double Мероприятие { get; set; }
        public string Пароль { get; set; }
        public string Фото { get; set; }
    
        public virtual Мероприятия Мероприятия { get; set; }
        public virtual Страны Страны { get; set; }
    }
}
